baseURL = "https://lsh0924.github.io/blog-test/"
languageCode = "en-us"
title = "춤뚜의 테스트 블로그"
theme = "hugo-theme-stack"

[params.defaultImage.opengraph]
enabled = false

[params.sidebar]
subtitle = "오호라 이것이 프로필"

[params.sidebar.avatar]
local = true
src = "img/avatar.png"

[[menu.main]]
identifier = "home"
name = "Home"
weight = -100
pre = "home"

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "archives"
weight = -90
pre = "archives"

[[menu.main]]
identifier = "search"
name = "Search"
url = "search"
weight = -70
pre = "search"

# content/post폴더 접근 path를 설정합니다.
[permalinks]
post = "/p/:slug/"
page = "/:slug"

# 포스팅 문서가 모여있는 루트 폴더를 설정합니다.
[params]
mainSections = ["post"]